### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by chriseidhof** [objcio/swift-talk-backend#46]
- [x] Turn off main site
- [x] Remove custom domain
- [x] Add custom domain to new Heroku app
- [x] Point DNS records to new Heroku app
- [x] Get database dump from rails
- [x] Clear swift database
- [x] Set BASE_URL environment variable for swift app (*without* trailing slash)
- [x] Migrate
- [x] Change github access token to the production credentials
- [x] Remove migration endpoint from code
- [ ] ...
